[package]

name = "nickel"
version = "0.1.0"
authors = [ "christoph@thoughtram.io" ]
description = "An express.js inspired web framework"
license = "MIT"

[profile.dev]
debug = false

[profile.test]
debug = false

[lib]

name = "nickel"
path = "src/lib.rs"

[dependencies.rust-mustache]

git = "https://github.com/nickel-org/rust-mustache.git"

[dependencies.nickel_macros]

path = "nickel_macros"

[dependencies]
url = "*"
time = "*"
typemap = "*"
plugin = "*"
regex = "*"
regex_macros = "*"
rustc-serialize = "*"
log = "*"
hyper = "*"
groupable = "*"

[[example]]

name = "example"
path = "examples/example.rs"

[[example]]

name = "example_with_default_router"
path = "examples/example_with_default_router.rs"

[[example]]

name = "example_template"
path = "examples/example_template.rs"

[[example]]

name = "macro_example"
path = "examples/macro_example.rs"

[[example]]

name = "hello_world"
path = "examples/hello_world.rs"

[[example]]

name = "example_route_data"
path = "examples/example_route_data.rs"
